// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tms-design/DarkIndigo.tsx": () => import("../components/mockups/tms-design/DarkIndigo.tsx"),
  "./components/mockups/tms-design/LightBlue.tsx": () => import("../components/mockups/tms-design/LightBlue.tsx")
};
